### ISSUE TITLE
SQLITE Error

### ISSUE THREAD

**Issue by Thulof** [xlzd/zhihu.photo#1]
when I run the app , there's something wrong.
Message : sqlite3.OperationalError: unable to open database file
what can i do to solve the problem?

( 听说Github上应该用英文，不知道对不对…… )

**Comment by xlzd** [comment]
那个 SQLite 文件是用来记录另一个网站抓取到的数据的，你去掉那部分代码吧。这段时间没空，等我空下来我会完全改写这些代码~

**Comment by Thulof** [comment]
好吧，谢谢。
去掉相关代码后跑起来了……
然而首页只有一行大字：“尊重版权，从你我做起”
……
……
……
T66y 在哪里……哭……

**Comment by xlzd** [comment]
哈哈，内容太少儿不宜了，所以隐藏了入口~
